### ISSUE TITLE
Problem when user has disabled modules in Brunch

### ISSUE THREAD

**Issue by stravid** [icholy/ember-handlebars-brunch#5]
I have disabled modules in Brunch:

```
modules:
    wrapper: false
    definition: false
```

This leads to an exception because `module` is not defined.
https://github.com/icholy/ember-handlebars-brunch/blob/master/src/index.coffee#L26

I would like to help fixing this. What approach do you suggest?

**Comment by icholy** [comment]
easiest way would probably be something like.

``` javascript
(typeof module !== 'undefined' ? module : {}).exports = /* handlebars */
```

But idk if people will be too keen on having that in their code if they're not even using modules.

what about another config property in `config.coffee`?

``` coffeescript
@exports = @config.files.templates.exports
@exports = "" if @exports is off
@exports = "module.exports = " if typeof @exports isnt 'string'
```

**Comment by icholy** [comment]
Feel free to open a PR.

**Comment by stravid** [comment]
Hmm... I think the config option is the better solution. Do you think Brunchs `@config.modules` could be used?

I will play around tomorrow and make a PR!

**Comment by icholy** [comment]
@stravid using `@config.modules.wrapper` is fine with me.

**Comment by icholy** [comment]
The only real problem is the way `module.id` is being used https://github.com/icholy/ember-handlebars-brunch/blob/master/src/index.coffee#L23
